<a href="https://colab.research.google.com/github/Aaaaddddyyyyyyyy/Machine-Learning-repo/blob/main/Classification_matrics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Accuaracy

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/content/heart.csv')

In [3]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [4]:
## Training esdt splitt the model
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=42)

In [5]:
## calling the two algorithms
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [6]:
## making the objects of two class
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [7]:
## training the 2 objects

clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [8]:
## making the prediction from the model
y_pred1= clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuarc of logistics regression :',accuracy_score(y_test,y_pred1))
print('Accuaracy of decisdion tree :',accuracy_score(y_test,y_pred2))

Accuarc of logistics regression : 0.7804878048780488
Accuaracy of decisdion tree : 0.9853658536585366

In [10]:
import pandas as pd
import numpy as np

In [11]:
df=pd.read_csv('/content/heart.csv')

df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=42)

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [14]:
## makong trhe class of the tewoq objectx
clf1=LogisticRegression()
clf2=DecisionTreeClassifier()

In [15]:
## training the modfel
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [16]:
## predicting the model
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score,confusion_matrix
print('Accuracy of Logistic regression : ',accuracy_score(y_test,y_pred1))
print('Accuracy of decciision tree : ',accuracy_score(y_test,y_pred2))

Accuracy of Logistic regression :  0.7804878048780488
Accuracy of decciision tree :  0.9853658536585366

Confusion matrix

In [18]:
import pandas as pd
import numpy as np

In [19]:
# confusion matrix
confusion_matrix(y_test,y_pred1)    # passing the parameters and true values

array([[70, 32],
       [13, 90]])

Confusion matrix for multi classification problem

In [20]:
import pandas as pd
import numpy as np

In [21]:
df=pd.read_csv('/content/Iris.csv')

In [22]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [23]:
from sklearn.model_selection import train_test_split    ## training the model
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,:-1],df.iloc[:,-1],test_size=0.2,random_state=24)

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor

In [25]:
## making the object class
clf1=LogisticRegression()
clf2=DecisionTreeRegressor()

In [26]:
from sklearn.preprocessing import LabelEncoder

# Encode target labels
le = LabelEncoder()
y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test) # Transform y_test with the same encoder

# Train the models with encoded labels
clf1.fit(X_train,y_train_encoded)
clf2.fit(X_train,y_train_encoded)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeRegressor()

In [27]:
y_pred1=clf1.predict(X_test)
y_pred2=clf2.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy score of logistic regression : ",accuracy_score(y_test,y_pred1))
print('Accuardy score of decison tree : ',accuracy_score(y_test,y_pred2))

Accuracy score of logistic regression :  0.0
Accuardy score of decison tree :  0.0

In [30]:
print('confusion matrix logistic regression \n')
conf_matrix_lr = confusion_matrix(y_test_encoded, y_pred1)
print(pd.DataFrame(conf_matrix_lr, columns=['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], index=['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']))

confusion matrix logistic regression

                 Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               10                0               0
Iris-versicolor            0                4               0
Iris-virginica             0                0              16